#!/bin/bash
input=$(cat)
file_path=$(echo "$input" | jq -r '.tool_input.file_path // empty')

if [[ "$file_path" == *"server/src/server/sql.gleam" ]]; then
  echo "BLOCKED: sql.gleam is generated by Squirrel. Edit SQL files in server/src/server/sql/ then run: gleam run -m squirrel" >&2
  exit 2
fi
exit 0
