-- Generated by scripts/generate_import.py from the Platser och
-- aktiviteter workbook. Do not edit by hand; re-run the generator instead.
--
-- Run this file first, then activities.sql. The TRUNCATE below wipes
-- ALL existing app data, including bookings, favourites, call-offs and
-- users (users are upserted again on login).
-- 31 locations have no Latitud/Longitud in the sheet; their coordinates are NULL below.
-- name_en/icon_name/color/icon_variant have no source column in the sheet; placeholders are used below and need manual review.

TRUNCATE
    booking,
    call_off,
    favourite,
    activity_user,
    activity_target_group,
    activity_tag_activity,
    activity_tag,
    activity,
    location_tag_location,
    location_tag,
    location,
    "user"
    CASCADE;

INSERT INTO location (
        id,
        name,
        name_en,
        description,
        description_en,
        icon_name,
        icon_variant,
        color,
        latitude,
        longitude,
        opening_hours
    )
VALUES
    (
        'f94f0920-a8c7-59c8-9599-0427cc9431a7',
        'Accenture',
        'Accenture',
        'Kom till Accenture-tältet för att lära er att äta smartare, minska svinn och skapa något eget. Kul, kreativt och hållbart!',
        'Kom till Accenture-tältet för att lära er att äta smartare, minska svinn och skapa något eget. Kul, kreativt och hållbart!',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.978805,
        14.133589,
        '{
            "2026-07-28": [
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "14:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '8d7dae67-b84d-57d4-b0cb-e15730f26dd0',
        'Aktivitetsbanken',
        'Aktivitetsbanken',
        'Aktiviteter man aldrig tröttnar på! Här finns kubb, bollar, jätteplockepinn och mer! Man kan slå sig ner i en solstol här. Alla spel går att låna för att ta med sig till sin by, kom bara ihåg att lämna tillbaka spelet inom kort. Häng här eller låna ett spel, i sammarbete med Lidl!',
        'Aktiviteter man aldrig tröttnar på! Här finns kubb, bollar, jätteplockepinn och mer! Man kan slå sig ner i en solstol här. Alla spel går att låna för att ta med sig till sin by, kom bara ihåg att lämna tillbaka spelet inom kort. Häng här eller låna ett spel, i sammarbete med Lidl!',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.978461,
        14.134235,
        '{
            "2026-07-26": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'fdadaadd-754d-5949-9342-4769d7ab3998',
        'Andrummet',
        'Andrummet',
        'Här finns plats för ro och samtal. Kom och häng, andas ut en sväng. Vi erbjuder samtal, pyssel och sällskap till de som behöver.',
        'Här finns plats för ro och samtal. Kom och häng, andas ut en sväng. Vi erbjuder samtal, pyssel och sällskap till de som behöver.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979734,
        14.133606,
        '{}'::jsonb
    ),
    (
        '571522f1-f8b9-528b-901b-af3478deeb7f',
        'Badbusstationen',
        'Badbusstationen',
        'Badbussar till stranden avgår här - se till att förboka er plats i appen eller vid Infotältet! Kom ihåg att ta med dig vattenflaska till stranden, och solskydd!',
        'Badbussar till stranden avgår här - se till att förboka er plats i appen eller vid Infotältet! Kom ihåg att ta med dig vattenflaska till stranden, och solskydd!',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.984824,
        14.133546,
        '{}'::jsonb
    ),
    (
        '9e43b7cf-35c9-5dba-9f38-4b643476d266',
        'Biblioteket',
        'Biblioteket',
        'Läs böcker, rita eller bara njut av tystnaden. I bibloteket håller vi en lägre ljudnivå och här kan du som behöver få njuta av lugnare aktiviteter.',
        'Läs böcker, rita eller bara njut av tystnaden. I bibloteket håller vi en lägre ljudnivå och här kan du som behöver få njuta av lugnare aktiviteter.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979693174712395,
        14.133602682364456,
        '{
            "2026-07-26": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '2e15db13-b14d-5764-b5b0-6183f70350a7',
        'Bönetorget',
        'Bönetorget',
        'Stadsdelstorg i Himalaya.',
        'Stadsdelstorg i Himalaya.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.97893,
        14.140551,
        '{}'::jsonb
    ),
    (
        'aa798fe8-2136-5d96-bf79-ce0fd48d1058',
        'Drömfångaren',
        'Drömfångaren',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979662,
        14.13325,
        '{
            "2026-07-26": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "21:00"}
            ]
        }'::jsonb
    ),
    (
        '4c7f98c1-b52f-5008-ac82-5a3b5b227683',
        'Fairtrade',
        'Fairtrade',
        'Besök Fairtrades banantält och lär er mer om hållbarhet och rättvisa! 🍌 I vårt tält är alla välkomna! Här kan scouterna lära sig mer om Fairtrade och få en inblick i hur flera av våra mest handlade varor produceras – och hur villkoren ser ut för många odlare världen över.',
        'Besök Fairtrades banantält och lär er mer om hållbarhet och rättvisa! 🍌 I vårt tält är alla välkomna! Här kan scouterna lära sig mer om Fairtrade och få en inblick i hur flera av våra mest handlade varor produceras – och hur villkoren ser ut för många odlare världen över.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.97853594418264,
        14.133940245823972,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "16:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "16:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "16:00"}
            ]
        }'::jsonb
    ),
    (
        '5b1aa9e9-91e5-5d82-83e1-dc1a543e6431',
        'Folkhögskolan',
        'Folkhögskolan',
        E'Kom och prata om allt som rör utbildning i Scouterna med oss. Vilken är din nästa kurs\x3F',
        E'Kom och prata om allt som rör utbildning i Scouterna med oss. Vilken är din nästa kurs\x3F',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979456695663885,
        14.134707299076785,
        '{
            "2026-07-26": [
                {"from": "09:00", "to": "18:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "18:00"}
            ]
        }'::jsonb
    ),
    (
        'cd1d325f-895e-59fc-aca6-8edafae56406',
        'Glaciärtorget',
        'Glaciärtorget',
        'Stadsdelstorg i Himalaya.',
        'Stadsdelstorg i Himalaya.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.978648,
        14.136217,
        '{}'::jsonb
    ),
    (
        '6bdd370f-54a0-5d41-a741-8c186aadfc5f',
        'Gnistan',
        'Gnistan',
        E'I demokratitältet Gnistan får det som glöder inom dig tid och utrymme. Delta i vårt program med scoutidoler och makthavare, och få en exklusiv pin. Eller kika förbi när som helst mellan 9\x3A30-23 för att hälla T-röd på det du brinner för!',
        E'I demokratitältet Gnistan får det som glöder inom dig tid och utrymme. Delta i vårt program med scoutidoler och makthavare, och få en exklusiv pin. Eller kika förbi när som helst mellan 9\x3A30-23 för att hälla T-röd på det du brinner för!',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.978829,
        14.133361,
        '{
            "2026-07-25": [
                {"from": "00:00", "to": "23:00"}
            ],
            "2026-07-26": [
                {"from": "09:30", "to": "18:00"}
            ],
            "2026-07-27": [
                {"from": "09:30", "to": "23:00"}
            ],
            "2026-07-28": [
                {"from": "09:30", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:30", "to": "23:00"}
            ],
            "2026-07-30": [
                {"from": "09:30", "to": "23:00"}
            ],
            "2026-07-31": [
                {"from": "09:30", "to": "12:00"}
            ]
        }'::jsonb
    ),
    (
        'cb2bf6cc-dda7-5fe6-980b-d9759d234da5',
        'Gunget',
        'Gunget',
        'Gungor att gunga på.',
        'Gungor att gunga på.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.98093,
        14.140532,
        '{}'::jsonb
    ),
    (
        '75e80b80-5215-59ac-a964-d79a634e2d1b',
        'Halmbalspyramiden',
        'Halmbalspyramiden',
        'Pyramid av halmbalar att klättra på och hänga på.',
        'Pyramid av halmbalar att klättra på och hänga på.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.981041,
        14.144428,
        '{}'::jsonb
    ),
    (
        'a164ffc2-aeaa-596a-af47-19fba36659cc',
        'Hantverket med Do-Redo',
        'Hantverket med Do-Redo',
        'Sy, sticka, skapa och var kreativ med Do-Redo! Med återbruk i fokus finns det många kunniga i Hantverket som hjälper dig med att göra kreativa kreationer. Du kan även laga din cykel i Cykelverkstaden.',
        'Sy, sticka, skapa och var kreativ med Do-Redo! Med återbruk i fokus finns det många kunniga i Hantverket som hjälper dig med att göra kreativa kreationer. Du kan även laga din cykel i Cykelverkstaden.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.97897792633006,
        14.134234009068011,
        '{
            "2026-07-26": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'a7e7685a-40cd-5044-839c-8a159424e1fc',
        'Heartbeat café',
        'Heartbeat café',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979465,
        14.133184,
        '{
            "2026-07-25": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "18:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "18:00"}
            ],
            "2026-08-01": [
                {"from": "09:00", "to": "16:00"}
            ]
        }'::jsonb
    ),
    (
        '7bf67cf4-c23f-5a00-b3d0-e75d843ea1d7',
        'Hinderbanan',
        'Hinderbanan',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.980547,
        14.142098,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "20:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "20:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "20:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "20:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-08-01": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'c2882eb1-387c-589b-acc6-91c485f3cbd9',
        'Hjärtat',
        'Hjärtat',
        'Hjärtat av lägret. Här hittar du våra partners, Pulsen du kan dansa i, Drömfångaren som bjuder på föreläsningar, Själen som är för alla olika livsåskådningsområden och du kan kika in hos Jamboree-Radion! Kom förbi och häng, prova på olika spontana aktiviteter eller kolla på uppträdanden. Läs mer om vad som finns att göra hos varje induiduell plats på kartan.',
        'Hjärtat av lägret. Här hittar du våra partners, Pulsen du kan dansa i, Drömfångaren som bjuder på föreläsningar, Själen som är för alla olika livsåskådningsområden och du kan kika in hos Jamboree-Radion! Kom förbi och häng, prova på olika spontana aktiviteter eller kolla på uppträdanden. Läs mer om vad som finns att göra hos varje induiduell plats på kartan.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979445,
        14.134174,
        '{}'::jsonb
    ),
    (
        '46c92f33-2b69-5a47-a445-0bdcf8016cac',
        'Hjärteträden',
        'Hjärteträden',
        'Träd dekorerade med hjärtan gjorda av deltagare från daglig verksamhet i Kristianstad.',
        'Träd dekorerade med hjärtan gjorda av deltagare från daglig verksamhet i Kristianstad.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979284,
        14.134331,
        '{}'::jsonb
    ),
    (
        'b5a57e2d-3bd2-5d53-aa1b-69635032074e',
        'Hägringen',
        'Hägringen',
        'Stadsdelstorg i Sahara.',
        'Stadsdelstorg i Sahara.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.98177,
        14.146291,
        '{}'::jsonb
    ),
    (
        'd112fc6c-7448-544a-a01d-5eea39ef3aaa',
        'Hänget',
        'Hänget',
        'Hängmattor att hänga i.',
        'Hängmattor att hänga i.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.978078,
        14.130838,
        '{}'::jsonb
    ),
    (
        '02a49763-f801-5ae0-b33c-1da63102ffec',
        'Iglootorget',
        'Iglootorget',
        'Stadsdelstorg i Himalaya.',
        'Stadsdelstorg i Himalaya.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.980557,
        14.140873,
        '{}'::jsonb
    ),
    (
        'e37d2577-496a-5981-b715-7f002e56b66a',
        'Infotält',
        'Infotält',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.97979851143169,
        14.134385999313892,
        '{
            "2026-07-25": [
                {"from": "08:30", "to": "18:00"}
            ],
            "2026-07-26": [
                {"from": "08:30", "to": "18:00"}
            ],
            "2026-07-27": [
                {"from": "08:30", "to": "18:00"}
            ],
            "2026-07-28": [
                {"from": "08:30", "to": "18:00"}
            ],
            "2026-07-29": [
                {"from": "08:30", "to": "18:00"}
            ],
            "2026-07-30": [
                {"from": "08:30", "to": "18:00"}
            ],
            "2026-07-31": [
                {"from": "08:30", "to": "18:00"}
            ],
            "2026-08-01": [
                {"from": "08:30", "to": "18:00"}
            ]
        }'::jsonb
    ),
    (
        '0e6237f7-fbc5-5234-8704-348b4b715aa9',
        'Jamboreeradio',
        'Jamboreeradio',
        'I Jamboreeradion blir det nedslag från hela lägerområdet, spännande gäster i studion, gött snack och musik som höjer stämningen - hela dagen. Upplev mer av Jamboree26 tillsammans med oss.',
        'I Jamboreeradion blir det nedslag från hela lägerområdet, spännande gäster i studion, gött snack och musik som höjer stämningen - hela dagen. Upplev mer av Jamboree26 tillsammans med oss.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.97962649697024,
        14.134395290933448,
        '{
            "2026-07-25": [
                {"from": "06:00", "to": "23:00"}
            ],
            "2026-07-26": [
                {"from": "06:00", "to": "23:00"}
            ],
            "2026-07-27": [
                {"from": "06:00", "to": "23:00"}
            ],
            "2026-07-28": [
                {"from": "06:00", "to": "23:00"}
            ],
            "2026-07-29": [
                {"from": "06:00", "to": "23:00"}
            ],
            "2026-07-30": [
                {"from": "06:00", "to": "23:00"}
            ],
            "2026-07-31": [
                {"from": "06:00", "to": "23:00"}
            ],
            "2026-08-01": [
                {"from": "06:00", "to": "23:00"}
            ]
        }'::jsonb
    ),
    (
        'bb915fad-3de8-5e84-86f0-8de5237d73a0',
        'Jamboreeshoppen',
        'Jamboreeshoppen',
        'Kom till shoppen och kika på Jamboreekollektionen, roliga pins och massa mer! Här finns smått och gott att komplettera lägerpackningen med och en och en annan souvernir att ta med hem.',
        'Kom till shoppen och kika på Jamboreekollektionen, roliga pins och massa mer! Här finns smått och gott att komplettera lägerpackningen med och en och en annan souvernir att ta med hem.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979013579900894,
        14.135512561731156,
        '{
            "2026-07-25": [
                {"from": "10:00", "to": "20:00"}
            ],
            "2026-07-26": [
                {"from": "10:00", "to": "18:30"}
            ],
            "2026-07-27": [
                {"from": "10:00", "to": "20:00"}
            ],
            "2026-07-28": [
                {"from": "10:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "10:00", "to": "20:00"}
            ],
            "2026-07-30": [
                {"from": "10:00", "to": "20:00"}
            ],
            "2026-07-31": [
                {"from": "10:00", "to": "19:00"}
            ]
        }'::jsonb
    ),
    (
        '84a2e13f-c773-53f0-8507-834843fd43dc',
        'Josbaren',
        'Josbaren',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979153,
        14.13368,
        '{
            "2026-07-25": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "18:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "18:00"}
            ],
            "2026-08-01": [
                {"from": "09:00", "to": "16:00"}
            ]
        }'::jsonb
    ),
    (
        'b071e99b-2445-55f4-bd1c-ae2542e67f71',
        'Klättertornet',
        'Klättertornet',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.97961582683232,
        14.134709905155816,
        '{
            "2026-07-26": [
                {"from": "08:30", "to": "12:00"},
                {"from": "14:00", "to": "17:30"}
            ],
            "2026-07-27": [
                {"from": "08:30", "to": "12:00"},
                {"from": "14:00", "to": "17:30"}
            ],
            "2026-07-28": [
                {"from": "08:30", "to": "12:00"},
                {"from": "14:00", "to": "17:30"}
            ],
            "2026-07-29": [
                {"from": "08:30", "to": "12:00"},
                {"from": "14:00", "to": "17:30"}
            ],
            "2026-07-30": [
                {"from": "08:00", "to": "12:00"},
                {"from": "14:00", "to": "17:30"}
            ],
            "2026-07-31": [
                {"from": "08:30", "to": "12:00"},
                {"from": "14:00", "to": "17:30"}
            ]
        }'::jsonb
    ),
    (
        'be185ee1-b3ad-53ac-b2be-90165776f853',
        'Kontignentstält - Canada',
        'Kontignentstält - Canada',
        'Väntar svar från Canada',
        'Väntar svar från Canada',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{}'::jsonb
    ),
    (
        '3b9ff44e-49ce-5bb3-99a5-9b886e0147a7',
        'Koralltorget',
        'Koralltorget',
        'Stadsdelstorg i Stora Barriärrevet.',
        'Stadsdelstorg i Stora Barriärrevet.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.978855,
        14.128261,
        '{}'::jsonb
    ),
    (
        'de3f2634-3ac3-52af-87ef-a56b77610659',
        'Ledarhänget',
        'Ledarhänget',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.980873,
        14.133829,
        '{}'::jsonb
    ),
    (
        'a04d0af4-43b8-509b-bbf3-2f237d5cb468',
        'Light My Fire',
        'Light My Fire',
        'Kom och gravera dina nya Light My Fire-produkter från shoppen med deras gravyrpenna! Här hålls även demos av bland annat tändstål och tävlingar i diverse scouttekniker.. Kom och testa!',
        'Kom och gravera dina nya Light My Fire-produkter från shoppen med deras gravyrpenna! Här hålls även demos av bland annat tändstål och tävlingar i diverse scouttekniker.. Kom och testa!',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.97893,
        14.13391,
        '{}'::jsonb
    ),
    (
        '29229fc1-7372-53c7-8766-7ce9c893af41',
        'Listening Ears',
        'Listening Ears',
        'Se info på tältet för aktuella öppettider.',
        'Se info på tältet för aktuella öppettider.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.97981549777961,
        14.134016331265492,
        '{
            "2026-07-25": [
                {"from": "13:00", "to": "16:30"},
                {"from": "18:30", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "13:00", "to": "16:30"},
                {"from": "18:30", "to": "21:00"}
            ],
            "2026-07-27": [
                {"from": "13:00", "to": "16:30"},
                {"from": "18:30", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "13:00", "to": "16:30"},
                {"from": "18:30", "to": "21:00"}
            ],
            "2026-07-29": [
                {"from": "13:00", "to": "16:30"},
                {"from": "18:30", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "13:00", "to": "16:30"},
                {"from": "18:30", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "13:00", "to": "16:30"},
                {"from": "18:30", "to": "21:00"}
            ],
            "2026-08-01": [
                {"from": "13:00", "to": "16:30"},
                {"from": "18:30", "to": "21:00"}
            ]
        }'::jsonb
    ),
    (
        '43d56564-0a21-5413-b4ba-9443cc09d1c9',
        'Lägerbålsscenen',
        'Lägerbålsscenen',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.983874,
        14.129213,
        '{
            "2026-07-25": [
                {"from": "20:00", "to": "21:00"}
            ]
        }'::jsonb
    ),
    (
        'fcd8b698-af4a-5880-8f70-00e1df575026',
        'Morakniv',
        'Morakniv',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.978908,
        14.133935,
        '{}'::jsonb
    ),
    (
        '77c0937b-a026-5a8c-bd8a-66ff58e84b4b',
        'NSF Klartänk & Drogfri',
        'NSF Klartänk & Drogfri',
        'Klartänkt & Drogfri är det 100 kvadratmeter stora tältet fyllt med de senaste trenderna inom arbetet mot ANDTS (Alkohol, narkotika, doping, tobak och spel). Här samlar NSF, (Nykterhetsrörelsens Scoutförbund), aktuella aktörer och TILLSAMMANS erbjuder vi en uppsjö av olika både roliga och lärorika aktiviteter. I tältet kommer det finnas allt från spelhörna, reflektionskortlekar, VR-glasögon, aktivitetstombola till en mega stor transferpress där en kan trycka sin egen medhavda tröja! Det här är platsen för dig som bara vill chilla och hänga en stund, ha roliga spel och aktiviteter att göra eller för dig som vill ta del av bra programmaterial inom ANDTS att använda hemma på kåren. Det är coolt att vara Klartänkt & Drogfri!',
        'Klartänkt & Drogfri är det 100 kvadratmeter stora tältet fyllt med de senaste trenderna inom arbetet mot ANDTS (Alkohol, narkotika, doping, tobak och spel). Här samlar NSF, (Nykterhetsrörelsens Scoutförbund), aktuella aktörer och TILLSAMMANS erbjuder vi en uppsjö av olika både roliga och lärorika aktiviteter. I tältet kommer det finnas allt från spelhörna, reflektionskortlekar, VR-glasögon, aktivitetstombola till en mega stor transferpress där en kan trycka sin egen medhavda tröja! Det här är platsen för dig som bara vill chilla och hänga en stund, ha roliga spel och aktiviteter att göra eller för dig som vill ta del av bra programmaterial inom ANDTS att använda hemma på kåren. Det är coolt att vara Klartänkt & Drogfri!',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.978822,
        14.13345,
        '{
            "2026-07-25": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "22:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-08-01": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '0996f1b8-14a0-5b7d-a3a5-e834bafba37f',
        'Oasen',
        'Oasen',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.97998,
        14.129319,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '929159a0-a77f-5287-b5c6-67846727c4f7',
        'Programtältet',
        'Programtältet',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.978782,
        14.133943,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "17:30"},
                {"from": "19:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "10:00", "to": "11:30"},
                {"from": "13:00", "to": "18:00"}
            ],
            "2026-07-27": [
                {"from": "10:00", "to": "11:30"},
                {"from": "13:00", "to": "17:30"},
                {"from": "19:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "10:00", "to": "11:30"},
                {"from": "13:00", "to": "17:30"}
            ],
            "2026-07-29": [
                {"from": "10:00", "to": "11:30"},
                {"from": "13:00", "to": "17:30"},
                {"from": "19:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "10:00", "to": "11:30"},
                {"from": "13:00", "to": "17:30"},
                {"from": "19:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "10:00", "to": "11:30"},
                {"from": "13:00", "to": "18:00"}
            ]
        }'::jsonb
    ),
    (
        'e7553093-8aa8-59cc-8ff3-017ffcf62464',
        'Pulsen',
        'Pulsen',
        'Funky och lika rött som hjärtat själv! Kom och dansa, lyssna på föreläsningar eller lär dig nya steg. Bidra till våra interaktiva tavlor, ta bilder med en kompis och behöver du en ny vän - kan du träffa en här!',
        'Funky och lika rött som hjärtat själv! Kom och dansa, lyssna på föreläsningar eller lär dig nya steg. Bidra till våra interaktiva tavlor, ta bilder med en kompis och behöver du en ny vän - kan du träffa en här!',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979172,
        14.133209,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-26": [
                {"from": "06:30", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "20:00", "to": "23:00"}
            ],
            "2026-07-27": [
                {"from": "06:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-28": [
                {"from": "06:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-29": [
                {"from": "06:00", "to": "12:00"},
                {"from": "14:00", "to": "17:30"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-30": [
                {"from": "06:30", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-31": [
                {"from": "06:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "22:00", "to": "23:00"}
            ]
        }'::jsonb
    ),
    (
        'c3fb5be8-be24-53d6-b69f-9cc8661312ec',
        'Pyramidtorget',
        'Pyramidtorget',
        'Stadsdelstorg i Sahara.',
        'Stadsdelstorg i Sahara.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.98082,
        14.141915,
        '{}'::jsonb
    ),
    (
        '9afd2343-f5f0-5890-9351-5b1b9caa53c8',
        'Regnbågstorget',
        'Regnbågstorget',
        'Stadsdelstorg i Amazonas.',
        'Stadsdelstorg i Amazonas.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979758,
        14.132831,
        '{}'::jsonb
    ),
    (
        'f06b6f75-2856-5dcc-b30b-4a1a1334e8fb',
        'Regntorget',
        'Regntorget',
        'Stadsdelstorg i Amazonas.',
        'Stadsdelstorg i Amazonas.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.980804,
        14.128584,
        '{}'::jsonb
    ),
    (
        '9d86cd5f-1577-5757-80a7-afbda678a256',
        'Roverhubben',
        'Roverhubben',
        'Roverhubben är en mötesplats för gemenskap, aktiviteter och nya upplevelser för roverscouter, alltså ledare och funktionärer i åldrarna 18-25 år. Här kan du träffa nya och gamla vänner, spela spel, pyssla, fika, lyssna på musik eller bara ta det lugnt en stund. Under dagarna och kvällarna finns något för både den som söker fart och gemenskap och den som behöver en lugn paus.',
        'Roverhubben är en mötesplats för gemenskap, aktiviteter och nya upplevelser för roverscouter, alltså ledare och funktionärer i åldrarna 18-25 år. Här kan du träffa nya och gamla vänner, spela spel, pyssla, fika, lyssna på musik eller bara ta det lugnt en stund. Under dagarna och kvällarna finns något för både den som söker fart och gemenskap och den som behöver en lugn paus.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.983334,
        14.139247,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "20:00"},
                {"from": "21:00", "to": "00:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "20:00"},
                {"from": "22:00", "to": "00:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"},
                {"from": "22:00", "to": "00:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "20:00"},
                {"from": "22:00", "to": "02:00"}
            ]
        }'::jsonb
    ),
    (
        '40e09906-53b3-5232-ba98-922a57643072',
        'Roverhubben - Bistron',
        'Roverhubben - Bistron',
        'Bistron är tältet i Roverhubben där du kan sitta och ta en fika vid roverscouterna egna Scoutbyrån-kafé eller sitta och jobba lite.',
        'Bistron är tältet i Roverhubben där du kan sitta och ta en fika vid roverscouterna egna Scoutbyrån-kafé eller sitta och jobba lite.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "20:00"},
                {"from": "21:00", "to": "00:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "20:00"},
                {"from": "22:00", "to": "00:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"},
                {"from": "22:00", "to": "00:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "20:00"},
                {"from": "22:00", "to": "02:00"}
            ]
        }'::jsonb
    ),
    (
        'eeadc5db-c4ae-55f0-abe4-14d86faa7886',
        'Roverhubben - Klubben',
        'Roverhubben - Klubben',
        'Klubben är tältet i Roverhubben där samtliga föreläsningar, workshops, quiz, karaoke och andra scenarrangemang sker för roverscouter!',
        'Klubben är tältet i Roverhubben där samtliga föreläsningar, workshops, quiz, karaoke och andra scenarrangemang sker för roverscouter!',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "20:00"},
                {"from": "21:00", "to": "00:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "20:00"},
                {"from": "22:00", "to": "00:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"},
                {"from": "22:00", "to": "00:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "20:00"},
                {"from": "22:00", "to": "02:00"}
            ]
        }'::jsonb
    ),
    (
        '9bb44458-5c86-56d1-a564-d2028497bac2',
        'Roverhubben - Loungen',
        'Roverhubben - Loungen',
        'Loungen är tälten i Roverhubben där du kan ta det lite lugnt, vila, testa lite spaaktiviteter eller prata med små bokstäver med ett par kompisar. Här sker även träningpass under vissa dagar!',
        'Loungen är tälten i Roverhubben där du kan ta det lite lugnt, vila, testa lite spaaktiviteter eller prata med små bokstäver med ett par kompisar. Här sker även träningpass under vissa dagar!',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "20:00"},
                {"from": "21:00", "to": "00:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "20:00"},
                {"from": "22:00", "to": "00:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"},
                {"from": "22:00", "to": "00:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "20:00"},
                {"from": "22:00", "to": "02:00"}
            ]
        }'::jsonb
    ),
    (
        'add09837-3faf-5ef1-a282-0c3001422d05',
        'Roverhubben - Pubben',
        'Roverhubben - Pubben',
        'Pubben är hjärtat av Roverhubben och är tältet där du kan testa lite spontana aktiviter, vara social, spela spel, eller prata med en Rover-som-lyssnar!',
        'Pubben är hjärtat av Roverhubben och är tältet där du kan testa lite spontana aktiviter, vara social, spela spel, eller prata med en Rover-som-lyssnar!',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "20:00"},
                {"from": "21:00", "to": "00:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "20:00"},
                {"from": "22:00", "to": "00:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"},
                {"from": "22:00", "to": "00:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "20:00"},
                {"from": "22:00", "to": "02:00"}
            ]
        }'::jsonb
    ),
    (
        '45522191-c8bf-517f-82e9-4fc2dee1b8af',
        'Roverprogram',
        'Roverprogram',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.983868,
        14.138016,
        '{
            "2026-07-27": [
                {"from": "08:30", "to": "12:30"},
                {"from": "14:00", "to": "18:00"}
            ],
            "2026-07-28": [
                {"from": "08:30", "to": "12:30"},
                {"from": "14:00", "to": "18:00"}
            ],
            "2026-07-29": [
                {"from": "08:30", "to": "12:30"},
                {"from": "14:00", "to": "18:00"}
            ],
            "2026-07-30": [
                {"from": "08:30", "to": "12:30"},
                {"from": "14:00", "to": "18:00"}
            ],
            "2026-07-31": [
                {"from": "08:30", "to": "12:30"},
                {"from": "14:00", "to": "18:00"}
            ]
        }'::jsonb
    ),
    (
        'c79377f3-7341-5185-8a36-98dc81e47aa1',
        'Scoutmuseet',
        'Scoutmuseet',
        'Tillsammans har vi ett särskilt scoutmuseum även på denna nationella jamboree som på flera storläger tidigare. Årets scoutmuseum fokuserar på lands-, riks- och förbundsläger och vi presenterar ett antal av dessa med en foto- och minnesutställning av 13 av dem. Det första är Djurgårdslägret 1912 och sedan är det ett urval av storläger fram till Jamboreen i Norra Åsum 2022. Vi kommer att visa en del annat också. Vi erbjuder spontana guidningar och även, om så önskas, guidade visningar gärna med en uppföljande diskussion om storlägerformatet.',
        'Tillsammans har vi ett särskilt scoutmuseum även på denna nationella jamboree som på flera storläger tidigare. Årets scoutmuseum fokuserar på lands-, riks- och förbundsläger och vi presenterar ett antal av dessa med en foto- och minnesutställning av 13 av dem. Det första är Djurgårdslägret 1912 och sedan är det ett urval av storläger fram till Jamboreen i Norra Åsum 2022. Vi kommer att visa en del annat också. Vi erbjuder spontana guidningar och även, om så önskas, guidade visningar gärna med en uppföljande diskussion om storlägerformatet.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979314529656314,
        14.13477895912246,
        '{
            "2026-07-26": [
                {"from": "08:30", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "08:30", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "08:30", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "08:30", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "08:30", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "08:30", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'ebeaedae-6be3-5b3c-a860-395d938ea741',
        'Signalen',
        'Signalen',
        E'Hälsa på radioscouterna och scouternas e-tjänstgrupp. Prova på amatörradiosändning, walkietalkie och andra roliga utmaningar med radioscouterna. Scouternas e-tjänster: Prova på programmering – för alla!\nHar du undrat hur man får en robot att lyda, eller hur riktig kod ser ut\x3F Kom till vårt tält och testa!\nHos oss kan du:\n🐍 Skriva ditt allra första program i Python – riktig kod, direkt i webbläsaren\n🐱 Bygga program med block i Scratch och göra ett litet spel\n🤖 Programmera en Lego Mindstorms-robot att hitta vägen till målet\n🚶 Förvandla en kompis till människorobot med träblock som kommandon\n🔐 Knäcka krypterade meddelanden, gissa avstånd, hitta gömda platser och testa hur bra du kan världens länder\nDu behöver inga förkunskaper – våra funktionärer finns på plats och hjälper dig igång.',
        E'Hälsa på radioscouterna och scouternas e-tjänstgrupp. Prova på amatörradiosändning, walkietalkie och andra roliga utmaningar med radioscouterna. Scouternas e-tjänster: Prova på programmering – för alla!\nHar du undrat hur man får en robot att lyda, eller hur riktig kod ser ut\x3F Kom till vårt tält och testa!\nHos oss kan du:\n🐍 Skriva ditt allra första program i Python – riktig kod, direkt i webbläsaren\n🐱 Bygga program med block i Scratch och göra ett litet spel\n🤖 Programmera en Lego Mindstorms-robot att hitta vägen till målet\n🚶 Förvandla en kompis till människorobot med träblock som kommandon\n🔐 Knäcka krypterade meddelanden, gissa avstånd, hitta gömda platser och testa hur bra du kan världens länder\nDu behöver inga förkunskaper – våra funktionärer finns på plats och hjälper dig igång.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979676,
        14.133416,
        '{
            "2026-07-26": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '1fc1da7c-a710-5602-ab33-196a548d9d4a',
        'Själen',
        'Själen',
        E'Behöver din själ få ta plats\x3F Själen bjuder in till något större. Här är alla livsåskådningar välkomna. Vårda din tro här och vidga dina vyer för att på bästa sätt få insyn och respektera andras.',
        E'Behöver din själ få ta plats\x3F Själen bjuder in till något större. Här är alla livsåskådningar välkomna. Vårda din tro här och vidga dina vyer för att på bästa sätt få insyn och respektera andras.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979754,
        14.133657,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-26": [
                {"from": "08:00", "to": "22:30"}
            ],
            "2026-07-27": [
                {"from": "08:00", "to": "22:30"}
            ],
            "2026-07-28": [
                {"from": "08:00", "to": "22:30"}
            ],
            "2026-07-29": [
                {"from": "08:00", "to": "22:30"}
            ],
            "2026-07-30": [
                {"from": "08:00", "to": "22:30"}
            ],
            "2026-07-31": [
                {"from": "08:00", "to": "22:30"}
            ]
        }'::jsonb
    ),
    (
        '2cd8199b-4070-5d1d-a016-11d58350e11d',
        'Soltorget',
        'Soltorget',
        'Stadsdelstorg i Sahara.',
        'Stadsdelstorg i Sahara.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.982806,
        14.143068,
        '{}'::jsonb
    ),
    (
        '694e7f0c-47c1-53e0-8419-442e85a31230',
        'Sparbanken',
        'Sparbanken',
        'Kom och häng hos oss på Sparbanken Skåne! Här kan ni sitta och ta det lugnt i våra sköna loungemöbler, tävla mot varandra i steggolf och corne hole samt göra vår budgettavla á la Lyxfällan.',
        'Kom och häng hos oss på Sparbanken Skåne! Här kan ni sitta och ta det lugnt i våra sköna loungemöbler, tävla mot varandra i steggolf och corne hole samt göra vår budgettavla á la Lyxfällan.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.978618957237096,
        14.133490955952775,
        '{
            "2026-07-27": [
                {"from": "14:00", "to": "18:00"}
            ],
            "2026-07-28": [
                {"from": "13:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "13:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '169af8b0-1294-55ab-a784-7f32e27bab29',
        'Spelarkaden',
        'Spelarkaden',
        'Möt era patrullkompisar, eller helt nya kompisar, i olika egentillverkade arkadspel.',
        'Möt era patrullkompisar, eller helt nya kompisar, i olika egentillverkade arkadspel.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979069,
        14.133397,
        '{
            "2026-07-26": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"},
                {"from": "19:00", "to": "22:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "12:00"},
                {"from": "14:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'bb919a84-8be9-5792-844e-096624ddfbf4',
        'Stimtorget',
        'Stimtorget',
        'Stadsdelstorg i Östersjön.',
        'Stadsdelstorg i Östersjön.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.981973,
        14.136063,
        '{}'::jsonb
    ),
    (
        'f99b57c2-9591-5822-ac46-baa5e7824b88',
        'Strandtorget',
        'Strandtorget',
        'Stadsdelstorg i Stora Barriärrevet.',
        'Stadsdelstorg i Stora Barriärrevet.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.976766,
        14.126727,
        '{}'::jsonb
    ),
    (
        '746d5d77-16dd-5725-b929-8ee2ab810002',
        'Swedish Food House',
        'Swedish Food House',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.978977883115405,
        14.134828599791419,
        '{
            "2026-07-25": [
                {"from": "12:00", "to": "22:00"}
            ],
            "2026-07-26": [
                {"from": "10:00", "to": "22:00"}
            ],
            "2026-07-27": [
                {"from": "10:00", "to": "22:00"}
            ],
            "2026-07-28": [
                {"from": "10:00", "to": "22:00"}
            ],
            "2026-07-29": [
                {"from": "10:00", "to": "22:00"}
            ],
            "2026-07-30": [
                {"from": "10:00", "to": "22:00"}
            ],
            "2026-07-31": [
                {"from": "10:00", "to": "22:00"}
            ],
            "2026-08-01": [
                {"from": "10:00", "to": "16:30"}
            ]
        }'::jsonb
    ),
    (
        '8feea8ec-fdc5-5b14-9f7d-da866ff69ad3',
        'the HERDS',
        'the HERDS',
        'Come and meet The HERDS, a groundbreaking public art project bringing life-sized animal puppets on an epic journey from the Congo Basin to the Arctic Circle, bringing audiences face to face with the climate crisis.',
        'Come and meet The HERDS, a groundbreaking public art project bringing life-sized animal puppets on an epic journey from the Congo Basin to the Arctic Circle, bringing audiences face to face with the climate crisis.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.978817,
        14.133582,
        '{}'::jsonb
    ),
    (
        '3f4448b7-1f98-5f72-8708-64fe98b240fb',
        'Tillsammansträdet',
        'Tillsammansträdet',
        'Träd för kårena att dekorera med något som representerar "tillsammans" för dom.',
        'Träd för kårena att dekorera med något som representerar "tillsammans" för dom.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.979838,
        14.13355,
        '{}'::jsonb
    ),
    (
        '3eacdce7-ef1e-5324-9ded-3bb1481a1267',
        'Trantorget',
        'Trantorget',
        'Stadsdelstorg i Östersjön.',
        'Stadsdelstorg i Östersjön.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.982532,
        14.140226,
        '{}'::jsonb
    ),
    (
        'ea849d41-331b-5bd6-804b-3194381f9c6a',
        'Träden',
        'Träden',
        'Bänkar att sitta på under träden.',
        'Bänkar att sitta på under träden.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.980753,
        14.1389,
        '{}'::jsonb
    ),
    (
        '897e8fd0-739e-5338-b517-cf2a55772fdf',
        'Upptäckarhubben',
        'Upptäckarhubben',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.980623,
        14.133059,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '7e0e57a6-2fe2-5032-b678-856ba7f05c9d',
        'Upptäckarhubben - Bikupan',
        'Upptäckarhubben - Bikupan',
        'Bikupan är platsen för fika och umgänge. Här kan du träffa kompisar och ta med dig den där glassen du köpte på caféet!',
        'Bikupan är platsen för fika och umgänge. Här kan du träffa kompisar och ta med dig den där glassen du köpte på caféet!',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '6403fed3-58ba-5b28-aba4-30771daad1de',
        'Upptäckarhubben - Draknästet',
        'Upptäckarhubben - Draknästet',
        'Draknästet är mystältet för dig som bara vill ta det lugnt med kompisarna.',
        'Draknästet är mystältet för dig som bara vill ta det lugnt med kompisarna.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '3d95a4a9-cdab-5bca-86e6-957b4237b0bd',
        'Upptäckarhubben - Gräset bakom pysslingen',
        'Upptäckarhubben - Gräset bakom pysslingen',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '49f819a9-e0c8-5c8f-8a51-cef17ac7c917',
        'Upptäckarhubben - infodisken',
        'Upptäckarhubben - infodisken',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'b7e3603c-9662-5942-b1d2-21b81371dedc',
        'Upptäckarhubben - Korpboet',
        'Upptäckarhubben - Korpboet',
        'Här finns det spel! Vill du utmana kompisen i brädspel är det här platsen för dig!',
        'Här finns det spel! Vill du utmana kompisen i brädspel är det här platsen för dig!',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'd39c294b-1391-5a94-9c88-66fa76fa4234',
        'Upptäckarhubben - Murmeldjuret',
        'Upptäckarhubben - Murmeldjuret',
        'Här är det låg volym som gäller, om du bara vill komma undan en stund.',
        'Här är det låg volym som gäller, om du bara vill komma undan en stund.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'd662996e-bc4f-5e4a-ba31-7fb278e15071',
        'Upptäckarhubben - Pysslingen',
        'Upptäckarhubben - Pysslingen',
        'Här finns pyssel och hantverk. En lugn plats där du kan sitta och pyssla, rita, och hålla på med hantverk som paracord och läder.',
        'Här finns pyssel och hantverk. En lugn plats där du kan sitta och pyssla, rita, och hålla på med hantverk som paracord och läder.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'f6eeb919-0a3e-5754-a786-e5f9c123d77c',
        'Upptäckarhubben - Scen',
        'Upptäckarhubben - Scen',
        'Upptäckarhubbens scen! Här kommer det att spelas livemusik, spelas musik och presenteras allmän information för alla på hubben.',
        'Upptäckarhubbens scen! Här kommer det att spelas livemusik, spelas musik och presenteras allmän information för alla på hubben.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'b0f0714b-6972-5a0c-a007-34a6cc1ec10a',
        'Upptäckarhubben - Skogen',
        'Upptäckarhubben - Skogen',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '9ae9d288-d5cf-5083-9de6-a641a4534bce',
        'Upptäckarhubben - Zvampen',
        'Upptäckarhubben - Zvampen',
        'Zvampen är partytältet för dig som gillar musik och dans, här finns det kul musik och en chans att festa loss.',
        'Zvampen är partytältet för dig som gillar musik och dans, här finns det kul musik och en chans att festa loss.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'c971648e-c1d6-53b0-9906-d7e20ae57a1e',
        'Utanför lägerområdet',
        'Utanför lägerområdet',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{}'::jsonb
    ),
    (
        'b904e6e9-2cb7-5ed6-98e8-2fee162c3ce7',
        'Utmanarhubben - Brädspelstält',
        'Utmanarhubben - Brädspelstält',
        'I Brädspelstältet kan du utmana kompisarna i brädspel, lägga pussel, pyssla eller prova någon av tältets andra aktiviteter. Här finns något för både små och stora grupper, och du är lika välkommen att komma själv som tillsammans med patrullen.',
        'I Brädspelstältet kan du utmana kompisarna i brädspel, lägga pussel, pyssla eller prova någon av tältets andra aktiviteter. Här finns något för både små och stora grupper, och du är lika välkommen att komma själv som tillsammans med patrullen.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "00:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "00:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "02:00"}
            ]
        }'::jsonb
    ),
    (
        '09dca4fa-54b3-5e5c-b73e-eb03e8a7e42b',
        'Utmanarhubben - Cafetält',
        'Utmanarhubben - Cafetält',
        'I Cafétältet kan du köpa fika, snacks och något gott att dricka. Perfekt när du behöver fylla på med energi inför nästa aktivitet eller vill ta med dig något till en fikastund i Paviljongen.',
        'I Cafétältet kan du köpa fika, snacks och något gott att dricka. Perfekt när du behöver fylla på med energi inför nästa aktivitet eller vill ta med dig något till en fikastund i Paviljongen.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "00:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "00:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "02:00"}
            ]
        }'::jsonb
    ),
    (
        '69c67fd6-b094-5839-b9f3-74c68393f3ed',
        'Utmanarhubben- Paviljongen',
        'Utmanarhubben- Paviljongen',
        'Paviljongen är Utmanarhubbens naturliga mötesplats för fika och umgänge. Här kan du slå dig ner vid ett bord, träffa vänner, äta det du köpt i Cafétältet och lyssna på Jamboree Radio i bakgrunden.',
        'Paviljongen är Utmanarhubbens naturliga mötesplats för fika och umgänge. Här kan du slå dig ner vid ett bord, träffa vänner, äta det du köpt i Cafétältet och lyssna på Jamboree Radio i bakgrunden.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "00:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "00:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "02:00"}
            ]
        }'::jsonb
    ),
    (
        'f22dd635-0dbd-5e7f-933d-5bbbb7aa5b76',
        'Utmanarhubben - Stora tältet',
        'Utmanarhubben - Stora tältet',
        'I Stora tältet arrangeras föreläsningar, samtal och större programpunkter. Under kvällarna höjs energin med musik, gemenskap och livligare aktiviteter. Här finns plats för både inspiration, nya perspektiv och riktigt bra häng.',
        'I Stora tältet arrangeras föreläsningar, samtal och större programpunkter. Under kvällarna höjs energin med musik, gemenskap och livligare aktiviteter. Här finns plats för både inspiration, nya perspektiv och riktigt bra häng.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "00:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "00:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "02:00"}
            ]
        }'::jsonb
    ),
    (
        '9a480199-30c2-5286-ae3e-e3372d36bd6a',
        'Utmanarhubben',
        'Utmanarhubben',
        'Utmanarhubben är en mötesplats för gemenskap, aktiviteter och nya upplevelser. Här kan du träffa nya och gamla vänner, spela spel, fika, lyssna på musik eller bara ta det lugnt en stund. Under dagarna och kvällarna finns något för både den som söker fart och gemenskap och den som behöver en lugn paus.',
        'Utmanarhubben är en mötesplats för gemenskap, aktiviteter och nya upplevelser. Här kan du träffa nya och gamla vänner, spela spel, fika, lyssna på musik eller bara ta det lugnt en stund. Under dagarna och kvällarna finns något för både den som söker fart och gemenskap och den som behöver en lugn paus.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.980511,
        14.126357,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "00:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "00:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "02:00"}
            ]
        }'::jsonb
    ),
    (
        '9a8595f4-39a5-50ac-8cd5-d6f17d834c51',
        'Utmanarhubben - Lilla scenen',
        'Utmanarhubben - Lilla scenen',
        'På Lilla scenen finns alltid något spännande på gång. Här kan du lyssna på inspirerande föreläsningar, tävla i quiz, sjunga karaoke eller upptäcka andra programpunkter. Samla kompisarna och se vad som händer – kanske blir det du som står på scen nästa gång.',
        'På Lilla scenen finns alltid något spännande på gång. Här kan du lyssna på inspirerande föreläsningar, tävla i quiz, sjunga karaoke eller upptäcka andra programpunkter. Samla kompisarna och se vad som händer – kanske blir det du som står på scen nästa gång.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "00:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "00:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "02:00"}
            ]
        }'::jsonb
    ),
    (
        'bf2bcd4d-f2e9-5a53-9ae7-792a70eafc09',
        'Utmanarhubben - Stora scenen',
        'Utmanarhubben - Stora scenen',
        'På Stora scenen händer det där lite extra. Här arrangeras konsert, livemusik, DJ-set, allsång och andra större programpunkter som fyller hubben med energi. Samla kompisarna, slå dig ner framför scenen eller dansa loss – här väntar några av Utmanarhubbens största upplevelser.',
        'På Stora scenen händer det där lite extra. Här arrangeras konsert, livemusik, DJ-set, allsång och andra större programpunkter som fyller hubben med energi. Samla kompisarna, slå dig ner framför scenen eller dansa loss – här väntar några av Utmanarhubbens största upplevelser.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{}'::jsonb
    ),
    (
        '4521bf30-25cd-55ed-9496-d32dd3c6136e',
        'Utmanarhubben samtalstält (flera små)',
        'Utmanarhubben samtalstält (flera små)',
        'Samtalstälten är en plats för lugna samtal, reflektion och återhämtning. Här kan du prata med patrullen, lära känna nya vänner eller komma undan från sorlet en stund. I området finns även Hängamattehörnan, och vid Samtalskortsutlämningen kan du låna samtalskort, filtar och annat som gör stunden extra mysig.',
        'Samtalstälten är en plats för lugna samtal, reflektion och återhämtning. Här kan du prata med patrullen, lära känna nya vänner eller komma undan från sorlet en stund. I området finns även Hängamattehörnan, och vid Samtalskortsutlämningen kan du låna samtalskort, filtar och annat som gör stunden extra mysig.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "00:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "00:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "00:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"},
                {"from": "21:00", "to": "02:00"}
            ]
        }'::jsonb
    ),
    (
        'ec2f83a4-52f5-5b91-900b-3aef97fcb04f',
        'Ålgrästorget',
        'Ålgrästorget',
        'Stadsdelstorg i Östersjön.',
        'Stadsdelstorg i Östersjön.',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.980545,
        14.136385,
        '{}'::jsonb
    ),
    (
        '7b537a33-1678-5ae7-8b46-c8d780969853',
        'Äventyrarhubben',
        'Äventyrarhubben',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        55.980814,
        14.135033,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'acfc3e8d-1bd4-51a6-9c0e-b0f58bc70650',
        'Äventyrarhubben - Bubblan',
        'Äventyrarhubben - Bubblan',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'fa9d8f0a-07a7-50f9-b1ec-7415c53a695d',
        'Äventyrarhubben - Forskardalen',
        'Äventyrarhubben - Forskardalen',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'ab3a5402-757f-5e5e-8588-3fcfbfa4c663',
        'Äventyrarhubben - Livliga Luckan',
        'Äventyrarhubben - Livliga Luckan',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'db698e3e-387a-5e3d-8dfd-08813f413863',
        'Äventyrarhubben - Ranchen',
        'Äventyrarhubben - Ranchen',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'd14b9e07-9155-5534-81c2-0cb4447aac3b',
        'Äventyrarhubben - Saloonen',
        'Äventyrarhubben - Saloonen',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '64fab0da-6496-5201-856c-f9ae82c89e72',
        'Äventyrarhubben - Skogsgläntan',
        'Äventyrarhubben - Skogsgläntan',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        'f1f39e79-f96a-5ee6-aff8-f842e4c00a44',
        'Äventyrarhubben - Soliga sällskapshörnan',
        'Äventyrarhubben - Soliga sällskapshörnan',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    ),
    (
        '887d5091-7fd1-563e-8b6f-165ec9f9d3b5',
        'Äventyrarhubben - Tågstationen',
        'Äventyrarhubben - Tågstationen',
        '',
        '',
        'tabler-map-pin',
        'outline',
        '#6b7280',
        NULL,
        NULL,
        '{
            "2026-07-25": [
                {"from": "14:00", "to": "21:00"}
            ],
            "2026-07-26": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-27": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-28": [
                {"from": "09:00", "to": "17:00"}
            ],
            "2026-07-29": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-30": [
                {"from": "09:00", "to": "21:00"}
            ],
            "2026-07-31": [
                {"from": "09:00", "to": "17:00"}
            ]
        }'::jsonb
    );
